### ISSUE TITLE
no collision

### ISSUE THREAD

**Issue by maxuehuai** [voxell-tech/GPUClothSimulationInUnity#2]
no collision

**Comment by nixon-voxell** [comment]
Hi, I think collision is only available in the CPU version. I think you can enable it through the collision checkbox.

**Comment by nixon-voxell** [comment]
Also wanted to say that this project is on pause so I can't update the source code right now. I'll make a post or some update when it is being continued.

**Comment by weiyu666** [comment]
Why is it suspended? No maintenance. Is GPU parallel data disordered during collision? Why do you have your own Json format in blender? Is there any problem with the vertex sorting of cloth mesh in the forum of unity? Is it because the algorithm of calculating shader to achieve PBD must be handled in this way?
![企业微信截图_a932c948-33fd-4601-b521-5f05a218f4ec](https://user-images.githubusercontent.com/22174508/220263362-c5aeca6e-3edb-46b5-8ed6-cfc59359d2a0.png)
![企业微信截图_596899a1-03e8-4274-9771-f49cc763a8f5](https://user-images.githubusercontent.com/22174508/220263391-bf5c5e5d-605d-4436-89f6-1ff36b28b73b.png)
